services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=messaging_app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=messaging_app
    depends_on:
      - db
    networks:
      - messaging_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: messaging_app
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - messaging_network

networks:
  messaging_network:

volumes:
  mysql_data:
