version: '3'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'message_db'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db_data:/var/lib/mysql
#      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_USER: 'root'
      DB_NAME: 'message_db'
      DB_PASSWORD: 'root'
      DB_HOST: 'db'
      DB_PORT: '3306'
    volumes:
      - .:/app
    depends_on:
      - db
      #      db:
      #        condition: service_healthy
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
      
volumes:
  db_data: